name: code_quality_report
description: Generate Code Climate JSON reports from dart Analysis Server. Transforms the output of dartanalyzer to GitLab code quality JSON

version: 1.0.0
homepage: https://github.com/adrianjagielak/code_quality_report

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  crypto: ^3.0.0

dev_dependencies:
  test: ^1.16.7

executables:
  tocodeclimate: